### ISSUE TITLE
retain file extension in filename df column?

### ISSUE THREAD

**Issue by morskyjezek** [jiaqili0803/ReConnect-ReCollect_Automation#10]
Hi @jiaqili0803 - would it be possible to retain the file extension in the column for filenames? But the part of the filename that is not the extension can still be the `public_id` field.

Maybe using the basename function on its own, not the splitext? I know that these are all `.xml` but it is possible that others would have different file extensions (like `.ead` perhaps)

**Comment by jiaqili0803** [comment]
will do!
