### ISSUE TITLE
Three files not parsing - thoughts?

### ISSUE THREAD

**Issue by morskyjezek** [jiaqili0803/ReConnect-ReCollect_Automation#2]
When I ran the analysis notebook, three files didn't work:

```
Error parsing file: xml-files/Clements Library - XML/dai_toa_senso_hoda_final.xml
Error parsing file: xml-files/Clements Library - XML/edwardsj_final.xml
Error parsing file: xml-files/Clements Library - XML/butcherl_final.xml
```

Any thoughts on what was going on with these?

**Comment by jiaqili0803** [comment]
these three clements xml files source files are broken, you can try to open these XML files in browser and see the error

**Comment by morskyjezek** [comment]
Got it. So they were supplied to us this way?

**Comment by jiaqili0803** [comment]
yes, only these three files are in this way, other files are good. I discussed with Chad and decided just to ignore these three

**Comment by morskyjezek** [comment]
That's strange. I think the problem is that the !DOCTYPE declaration (line 2) is not correctly formatted. Your code appears to process them correctly when I changed it to the following:

```
<!DOCTYPE ead PUBLIC "+//ISBN 1-931666-00-8//DTD ead.dtd (Encoded Archival Description (EAD) Version 2002)//EN" "ead.dtd">
```

The files we received appear to have an internal system declaration - I don't know why, and the lines were displaying as:

```
<!DOCTYPE ead SYSTEM "ead.dtd" PUBLIC "+//ISBN 1-931666-00-8//DTD ead.dtd (Encoded Archival Description (EAD) Version 2002)//EN">
```

It has something to do with the way that XML documents process the "dtd" declaration, which define the structure of the document. As I understand it, it's an older approach. Fortunately, only the Clements appears to be using this approach and the others are referencing XML schemas.

**Comment by jiaqili0803** [comment]
Thank you for pointing out that!! I will take a look into that! I will try to manually modify the DOCTYPE declaration section of these three files and add the results of these three files.

**Comment by morskyjezek** [comment]
Great. I think it will work. I was able to process them on my local copy. Hopefully works for you too.
