### ISSUE TITLE
Visualization possibilities

### ISSUE THREAD

**Issue by morskyjezek** [jiaqili0803/ReConnect-ReCollect_Automation#3]
I've been looking through this post on options for visualizing wordcount data in various ways - https://towardsdatascience.com/beyond-the-cloud-4-visualizations-to-use-instead-of-word-cloud-960dd516f215. It looks like we could do some similar visualizations using the plotly. 

@jiaqili0803 - When we meet on Monday, could we discuss the feasibility of creating something like this? Specifically, I am wondering about options to parse out the counts based on what tag containers they occur within. For example, a series of stacked bar charts that show occurence of terms within the `controlaccess` element (that is, any occurrences within `geogname`, `subject`, `corpname`, and `genreform`, though it doesn't seem like any appear in the last tag at the moment) and then some of the other elements that are more narrative text (that is,  `abstract`, `bioghist`, and `scopecontent`).

**Comment by morskyjezek** [comment]
I am wondering specifically if we might adapt the grid of stacked bar charts, the "sunburst" design they use, and/or the "treemap". Don't worry about putting these together before we meet, I'd like to get any idea of your thoughts on whether these would work with this data?

**Comment by jiaqili0803** [comment]
done!

**Comment by jiaqili0803** [comment]
done!
