### ISSUE TITLE
EAD_id extraction producing extra lines

### ISSUE THREAD

**Issue by morskyjezek** [jiaqili0803/ReConnect-ReCollect_Automation#5]
In the function that is creating the term match output lists, the ead_ID extraction seems to be pulling in some blank lines. See the `matched_results_Clements.csv` on lines 10 & 11 for example (the ID is "umich-wcl-F-696tow" and there is a line split and it is escaped by double quotes). Is it possible to clean this up?

**Comment by jiaqili0803** [comment]
thank you for pointing that out! I didnot find the line split as you mentioned, can we have a 5min discussion after today's meeting about this?

**Comment by jiaqili0803** [comment]
fixed! It's because the source file has an extra space to the right of the ">" in the eadid section: .... .encodinganalog="Identifier"> umich-wcl-F-696tow</eadid>......seems that there are still possibilities of making these mistakes in the process of making ead files (?)

**Comment by morskyjezek** [comment]
Strange. I don't know why that would happen either. Probably a data entry issue? We could ask their metadata people.

**Comment by jiaqili0803** [comment]
I added the strip() in the code to fix this issue, I think this is good for now! Yeah I do think it might be a data entry issue
