### ISSUE TITLE
Match using word boundaries?

### ISSUE THREAD

**Issue by morskyjezek** [jiaqili0803/ReConnect-ReCollect_Automation#6]
@jiaqili0803 - I'm noting a few places where we may want to use word boundary matches. This may be possible with regex. What do you think?  

For example, in the Clements matched set, "Moro" matches for "Morocco". So it does match the string but is not what we're looking for in this case.

**Comment by jiaqili0803** [comment]
yeah! I agree! I will add some tokenization and data cleaning steps to help improve this!
