### ISSUE TITLE
Request: include titleproper in the matched_results report?

### ISSUE THREAD

**Issue by morskyjezek** [jiaqili0803/ReConnect-ReCollect_Automation#8]
Sorry, another request that came up while I was looking through the reports.

Would it be possible to include the `titleproper` tag from the EAD in the match reports?

**Comment by morskyjezek** [comment]
The reason I was asking for the filename and also this is because the internal identifiers and filenaming variations make it more difficult to go back and look at the context where the term matched from.

**Comment by jiaqili0803** [comment]
done!
